### ISSUE TITLE
大佬，能用这个修改无线mac让校园网把路由器识别成移动设备吗，我们学校只能无线桥接

### ISSUE THREAD

**Issue by rrkistch** [Subdue0/changewmac#1]
大佬，能用这个修改无线mac让校园网把路由器识别成移动设备吗，我们学校只能无线桥接

**Comment by xdhgsq** [comment]
mac只是地址而已，改mac地址是为了解决一些mac地址黑名单问题，你想把路由识别为移动设备，估计要去修改UA，这个不适合你
